# Generated by Django 5.1.7 on 2025-03-25 21:20

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='cpf_invalido', message='Número de CPF precisa ter apenas números e 11 deles.', regex='^\\d{11}$'), app.models.validadorDeCPF])),
                ('numeroSUS', models.PositiveIntegerField(unique=True)),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('cep', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(code='cep_invalido', message='Número de CEP ter apenas números e 8 deles.', regex='\\d{8}$')])),
                ('endereço', models.CharField(max_length=100)),
                ('dataNascimento', models.DateField(help_text='Data de nascimento pode estar entre 0 dias e 150 anos atrás.', validators=[app.models.validadorDataNascimento])),
                ('generoNascimento', models.CharField(choices=[('H', 'Homem'), ('M', 'Mulher')], default='H', max_length=1)),
                ('generoIdentificação', models.CharField(blank=True, max_length=20)),
                ('tipoSanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
            ],
        ),
    ]
