# Generated by Django 5.1.3 on 2025-05-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacina',
            options={'verbose_name': 'Vacinas homologadas', 'verbose_name_plural': 'Vacinas homologadas'},
        ),
        migrations.AlterModelOptions(
            name='vacinas',
            options={'verbose_name': 'Carteirinha de vacinas por paciente', 'verbose_name_plural': 'Carteirinha de vacinas por paciente'},
        ),
        migrations.AlterField(
            model_name='cid',
            name='descricao',
            field=models.CharField(help_text='Descrição da doença', max_length=250),
        ),
        migrations.AlterField(
            model_name='vacinas',
            name='data_aplicacao',
            field=models.DateField(help_text='Data de aplicação', verbose_name='Data'),
        ),
    ]
