# Generated by Django 5.1.7 on 2025-03-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_paciente_cep_alter_paciente_cpf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anemia',
            options={'verbose_name': 'Marcadores de Anemia', 'verbose_name_plural': 'Marcadores de Anemias'},
        ),
        migrations.AlterModelOptions(
            name='documentomedico',
            options={'verbose_name': 'Documento médico', 'verbose_name_plural': 'Documentos médicos'},
        ),
        migrations.AlterModelOptions(
            name='dsts',
            options={'verbose_name': 'Sorologias de DST', 'verbose_name_plural': 'Sorologias de DSTs'},
        ),
        migrations.AlterModelOptions(
            name='funcaohepatica',
            options={'verbose_name': 'Função Hepática', 'verbose_name_plural': 'Funções Hepáticas'},
        ),
        migrations.AlterModelOptions(
            name='funcaorenal',
            options={'verbose_name': 'Função Renal', 'verbose_name_plural': 'Funções Renais'},
        ),
        migrations.AlterModelOptions(
            name='funcaotireoide',
            options={'verbose_name': 'Parâmetros Tireoide', 'verbose_name_plural': 'Parâmetros Tireoides'},
        ),
        migrations.AlterModelOptions(
            name='glicemia',
            options={'verbose_name': 'Glicemia', 'verbose_name_plural': 'Glicemias'},
        ),
        migrations.AlterModelOptions(
            name='hemogramacompleto',
            options={'verbose_name': 'Hemograma Completo', 'verbose_name_plural': 'Hemogramas Completos'},
        ),
        migrations.AlterModelOptions(
            name='hormonais',
            options={'verbose_name': 'Taxa Hormonal', 'verbose_name_plural': 'Taxas Hormonais'},
        ),
        migrations.AlterModelOptions(
            name='marcadoresinflamacao',
            options={'verbose_name': 'Marcadores de Inflamação', 'verbose_name_plural': 'Marcadores de Inflamações'},
        ),
        migrations.AlterModelOptions(
            name='sorologias',
            options={'verbose_name': 'Outras Sorologias', 'verbose_name_plural': 'Outras Sorologias'},
        ),
        migrations.RemoveIndex(
            model_name='documentomedico',
            name='app_documen_pacient_29eb8c_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentomedico',
            name='app_documen_tipo_ar_de6b2e_idx',
        ),
        migrations.RemoveField(
            model_name='documentomedico',
            name='clinician_notes',
        ),
        migrations.RemoveField(
            model_name='documentomedico',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='documentomedico',
            name='tamanho_arquivo',
        ),
        migrations.AddField(
            model_name='documentomedico',
            name='anotacaoMedico',
            field=models.TextField(blank=True, verbose_name='Anotação do Médico'),
        ),
        migrations.AddField(
            model_name='documentomedico',
            name='tipoDocumento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de documento'),
        ),
    ]
