# Generated by Django 5.1.3 on 2025-05-12 23:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_vacina_options_alter_vacinas_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroVacinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplicacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('dose', models.PositiveSmallIntegerField(default=1)),
                ('lote_aplicado', models.CharField(blank=True, max_length=50, null=True)),
                ('local_aplicacao', models.CharField(blank=True, max_length=100, null=True)),
                ('profissional', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to='app.fichacadastral')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.vacina')),
            ],
            options={
                'verbose_name': 'Registro de Vacinação',
                'verbose_name_plural': 'Registros de Vacinação',
                'unique_together': {('paciente', 'vacina', 'dose')},
            },
        ),
        migrations.DeleteModel(
            name='Vacinas',
        ),
    ]
