# Generated by Django 5.1.7 on 2025-03-27 23:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_anemia_options_alter_documentomedico_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentomedico',
            name='arquivo',
            field=models.FileField(help_text='Aceita apenas PDF e JPEG', upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpeg'])]),
        ),
    ]
