# Generated by Django 5.1.7 on 2025-04-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_documentomedico_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsts',
            name='sorologiaHerpes',
        ),
        migrations.AddField(
            model_name='dsts',
            name='sorologiaHerpesIGC',
            field=models.BooleanField(blank=True, help_text='reativo?', null=True, verbose_name='Sorologia Herpes IgC'),
        ),
        migrations.AddField(
            model_name='dsts',
            name='sorologiaHerpesIGM',
            field=models.BooleanField(blank=True, help_text='reativo?', null=True, verbose_name='Sorologia Herpes IgM'),
        ),
        migrations.AlterField(
            model_name='dsts',
            name='antihbc',
            field=models.BooleanField(blank=True, help_text='reativo?', null=True, verbose_name='Anti-HBc'),
        ),
        migrations.AlterField(
            model_name='dsts',
            name='antihbs',
            field=models.BooleanField(blank=True, help_text='reativo?', null=True, verbose_name='Anti-HBs'),
        ),
        migrations.AlterField(
            model_name='dsts',
            name='antihcv',
            field=models.BooleanField(blank=True, help_text='reativo?', null=True, verbose_name='Anti-HCV'),
        ),
        migrations.AlterField(
            model_name='dsts',
            name='clamidia',
            field=models.BooleanField(blank=True, help_text='reativo?', null=True, verbose_name='Clamídia'),
        ),
        migrations.AlterField(
            model_name='dsts',
            name='ftaabsOUtpha',
            field=models.BooleanField(blank=True, help_text='reativo?', null=True, verbose_name='FTA-ABS/TPHA'),
        ),
        migrations.AlterField(
            model_name='dsts',
            name='gonorreia',
            field=models.BooleanField(blank=True, help_text='reativo?', null=True, verbose_name='Gonorreia'),
        ),
        migrations.AlterField(
            model_name='dsts',
            name='hbsag',
            field=models.BooleanField(blank=True, help_text='reativo?', null=True, verbose_name='HBsAg'),
        ),
        migrations.AlterField(
            model_name='dsts',
            name='hiv',
            field=models.BooleanField(blank=True, help_text='reativo?', null=True, verbose_name='HIV'),
        ),
        migrations.AlterField(
            model_name='dsts',
            name='vdrlOUrpr',
            field=models.BooleanField(blank=True, help_text='reativo?', null=True, verbose_name='VDRL/RPR'),
        ),
        migrations.AlterField(
            model_name='sorologias',
            name='antiCCP',
            field=models.BooleanField(blank=True, help_text='reativo?', null=True, verbose_name='Anti-CCP'),
        ),
        migrations.AlterField(
            model_name='sorologias',
            name='antiDNA',
            field=models.BooleanField(blank=True, help_text='reativo?', null=True, verbose_name='Anti-DNA dupla hélice'),
        ),
        migrations.AlterField(
            model_name='sorologias',
            name='anticorpoAntinuclear',
            field=models.BooleanField(blank=True, help_text='reativo?', null=True, verbose_name='Anticorpo Antinuclear'),
        ),
        migrations.AlterField(
            model_name='sorologias',
            name='chagas',
            field=models.BooleanField(blank=True, help_text='reativo?', null=True, verbose_name='Doença de Chagas'),
        ),
        migrations.AlterField(
            model_name='sorologias',
            name='chikungunya',
            field=models.BooleanField(blank=True, help_text='reativo?', null=True, verbose_name='Chikungunya'),
        ),
        migrations.AlterField(
            model_name='sorologias',
            name='citomegalovirus',
            field=models.BooleanField(blank=True, help_text='reativo?', null=True, verbose_name='Citomegalovírus'),
        ),
        migrations.AlterField(
            model_name='sorologias',
            name='covid19',
            field=models.BooleanField(blank=True, help_text='reativo?', null=True, verbose_name='Covid19'),
        ),
        migrations.AlterField(
            model_name='sorologias',
            name='dengue',
            field=models.BooleanField(blank=True, help_text='reativo?', null=True, verbose_name='Dengue'),
        ),
        migrations.AlterField(
            model_name='sorologias',
            name='ebv',
            field=models.BooleanField(blank=True, help_text='reativo?', null=True, verbose_name='Epstein-Barr Vírus'),
        ),
        migrations.AlterField(
            model_name='sorologias',
            name='fatorReumatoide',
            field=models.BooleanField(blank=True, help_text='reativo?', null=True, verbose_name='Fator Reumatoide'),
        ),
        migrations.AlterField(
            model_name='sorologias',
            name='febreTifoide',
            field=models.BooleanField(blank=True, help_text='reativo?', null=True, verbose_name='Febre Tifoide'),
        ),
        migrations.AlterField(
            model_name='sorologias',
            name='leptospirose',
            field=models.BooleanField(blank=True, help_text='reativo?', null=True, verbose_name='Leptospirose'),
        ),
        migrations.AlterField(
            model_name='sorologias',
            name='rubeola',
            field=models.BooleanField(blank=True, help_text='reativo?', null=True, verbose_name='Rubeola'),
        ),
        migrations.AlterField(
            model_name='sorologias',
            name='toxoplasmose',
            field=models.BooleanField(blank=True, help_text='reativo?', null=True, verbose_name='Toxoplasmose'),
        ),
        migrations.AlterField(
            model_name='sorologias',
            name='zikaVirus',
            field=models.BooleanField(blank=True, help_text='reativo?', null=True, verbose_name='Zika Virus'),
        ),
    ]
