# Generated by Django 5.1.3 on 2025-05-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_fichacadastral_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examelaboratorial',
            options={'verbose_name': 'Exame Laboratorial', 'verbose_name_plural': 'Exame Laboratoriais'},
        ),
    ]
