# Generated by Django 5.1.7 on 2025-04-16 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_dsts_sorologiaherpes_dsts_sorologiaherpesigc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código da doença', max_length=8, unique=True, verbose_name='CID')),
                ('descricao', models.CharField(help_text='Descrição da doença', max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='cid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cid', verbose_name='Código CID'),
        ),
        migrations.CreateModel(
            name='Receituario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data de emissão receituário', verbose_name='Data')),
                ('remedio', models.CharField(blank=True, help_text='Remédio prescrito', max_length=30, null=True)),
                ('crm', models.CharField(max_length=15, verbose_name='CRM do médico')),
                ('nomeDoMedico', models.CharField(max_length=50, verbose_name='Nome do médico')),
                ('textoReceituario', models.CharField(blank=True, max_length=200, null=True, verbose_name='Texto do receituário')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cid', verbose_name='Código da doença')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente', verbose_name='Paciente')),
            ],
        ),
    ]
