# Generated by Django 5.1.7 on 2025-04-16 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cid_paciente_cid_receituario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compostoAtivo', models.CharField(max_length=50, verbose_name='Composto ativo')),
                ('dosagem', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dosagem')),
            ],
        ),
        migrations.AlterField(
            model_name='receituario',
            name='textoReceituario',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Texto do receituário, período de tratamento, sugestão de uso'),
        ),
        migrations.AlterField(
            model_name='receituario',
            name='remedio',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='app.remedio', verbose_name='Remedio'),
        ),
    ]
